import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { v4 as uuid } from 'uuid';
import { StoreService } from '../store/store.service';
import { NotificationsService } from '../notifications/notifications.service';
@Injectable()
export class MessagesService {
 constructor(private store:StoreService, private notifications:NotificationsService){}
 async listingThread(userId:string,listingId:string){const listing=await this.store.findById('listings',listingId);if(!listing)throw new NotFoundException('Listing not found');const msgs=await this.store.all('messages');const participant=listing.agentId===userId||msgs.some(m=>m.listingId===listingId&&(m.senderId===userId||m.receiverId===userId));if(!participant)throw new ForbiddenException('You are not a participant in this listing conversation');return msgs.filter(m=>m.listingId===listingId&&(m.senderId===userId||m.receiverId===userId)).sort((a,b)=>new Date(a.createdAt).getTime()-new Date(b.createdAt).getTime());}
 async generalThread(userId:string,otherUserId:string){const other=await this.store.findById('users',otherUserId);if(!other)throw new NotFoundException('User not found');const all=await this.store.all('messages');return all.filter(m=>!m.listingId&&((m.senderId===userId&&m.receiverId===otherUserId)||(m.senderId===otherUserId&&m.receiverId===userId))).sort((a,b)=>new Date(a.createdAt).getTime()-new Date(b.createdAt).getTime());}
 async inbox(userId:string){const all=await this.store.all('messages');const mine=all.filter(m=>m.senderId===userId||m.receiverId===userId);const byThread:Record<string,any>={};mine.forEach(m=>{const otherId=m.senderId===userId?m.receiverId:m.senderId;const key=m.listingId?`listing:${m.listingId}`:`general:${otherId}`;if(!byThread[key]||new Date(m.createdAt)>new Date(byThread[key].createdAt))byThread[key]=m;});return Promise.all(Object.values(byThread).map(async(m:any)=>{const otherId=m.senderId===userId?m.receiverId:m.senderId;const other=await this.store.findById('users',otherId);const listing=m.listingId?await this.store.findById('listings',m.listingId):null;return{listingId:m.listingId||null,otherUserId:otherId,listingTitle:listing?.title||(other?.role==='admin'?'Admin support':'General'),otherUserName:other?.name,lastMessage:m.body,time:m.createdAt};}));}
 async send(senderId:string,body:any){const receiverId=String(body.receiverId||'');const messageBody=String(body.body||'').trim();if(!receiverId||!messageBody)throw new BadRequestException('receiverId and body are required');if(receiverId===senderId)throw new BadRequestException('You cannot message yourself');const receiver=await this.store.findById('users',receiverId);if(!receiver)throw new NotFoundException('Receiver not found');let listingId=body.listingId||null;if(listingId){const listing=await this.store.findById('listings',listingId);if(!listing)throw new NotFoundException('Listing not found');const allowed=listing.agentId===senderId||listing.agentId===receiverId;if(!allowed){const txns=await this.store.all('transactions');const rented=txns.some(t=>t.listingId===listingId&&t.renterId===senderId&&t.status==='completed');if(!rented)throw new ForbiddenException('You are not authorized to message about this listing');}}
 const message={id:uuid(),listingId,senderId,receiverId,body:messageBody.slice(0,5000),createdAt:new Date().toISOString(),read:false};await this.store.insert('messages',message); await this.notifications.create(receiver.id,'New Foltrest message',`${(await this.store.findById('users',senderId))?.name||'Someone'} sent you a message.`,'message',receiver.email); return message;}
 async all(){return this.store.all('messages');}
}
